
# parsetab.py
# This file is automatically generated. Do not edit.
_tabversion = '3.2'

_lr_method = 'LALR'

_lr_signature = '\x8fB\xbfa\x01\xe3\xcf\xa1"\x8f\xaa\xe2\xdc\xe8\xb62'
    
_lr_action_items = {'Keyword':([0,2,4,10,11,12,13,14,],[1,1,1,1,1,1,1,1,]),')':([1,7,8,9,15,17,18,19,20,],[-9,-10,-7,15,-8,-4,-3,-5,-6,]),'(':([0,2,4,10,11,12,13,14,],[4,4,4,4,4,4,4,4,]),'+':([1,5,6,7,8,9,15,16,17,18,19,20,],[-9,-10,12,-10,-7,12,-8,12,-4,-3,-5,-6,]),'*':([1,5,6,7,8,9,15,16,17,18,19,20,],[-9,-10,13,-10,-7,13,-8,13,13,13,-5,-6,]),'-':([0,1,2,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19,20,],[2,-9,2,2,-10,11,-10,-7,11,2,2,2,2,2,-8,11,-4,-3,-5,-6,]),'/':([1,5,6,7,8,9,15,16,17,18,19,20,],[-9,-10,14,-10,-7,14,-8,14,14,14,-5,-6,]),'Identifier':([0,2,4,10,11,12,13,14,],[5,7,7,7,7,7,7,7,]),'=':([5,],[10,]),'$end':([1,3,5,6,7,8,15,16,17,18,19,20,],[-9,0,-10,-2,-10,-7,-8,-1,-4,-3,-5,-6,]),}

_lr_action = { }
for _k, _v in _lr_action_items.items():
   for _x,_y in zip(_v[0],_v[1]):
      if not _x in _lr_action:  _lr_action[_x] = { }
      _lr_action[_x][_k] = _y
del _lr_action_items

_lr_goto_items = {'expression':([0,2,4,10,11,12,13,14,],[6,8,9,16,17,18,19,20,]),'statement':([0,],[3,]),}

_lr_goto = { }
for _k, _v in _lr_goto_items.items():
   for _x,_y in zip(_v[0],_v[1]):
       if not _x in _lr_goto: _lr_goto[_x] = { }
       _lr_goto[_x][_k] = _y
del _lr_goto_items
_lr_productions = [
  ("S' -> statement","S'",1,None,None,None),
  ('statement -> Identifier = expression','statement',3,'p_statement_assign','untitled.py',161),
  ('statement -> expression','statement',1,'p_statement_expr','untitled.py',165),
  ('expression -> expression + expression','expression',3,'p_expression_binop','untitled.py',169),
  ('expression -> expression - expression','expression',3,'p_expression_binop','untitled.py',170),
  ('expression -> expression * expression','expression',3,'p_expression_binop','untitled.py',171),
  ('expression -> expression / expression','expression',3,'p_expression_binop','untitled.py',172),
  ('expression -> - expression','expression',2,'p_expression_uminus','untitled.py',179),
  ('expression -> ( expression )','expression',3,'p_expression_group','untitled.py',183),
  ('expression -> Keyword','expression',1,'p_expression_number','untitled.py',187),
  ('expression -> Identifier','expression',1,'p_expression_name','untitled.py',191),
]
